set working-directory := '..'

rf *ARGS:
    uv run python train/train_rf.py {{ARGS}}

lgbm *ARGS:
    uv run python train/train_lgbm.py {{ARGS}}

plot *ARGS:
    uv run python train/plot_results.py {{ARGS}}
